media:
  input: public
  output: /

content:
  - name: posts
    label: Posts
    type: collection
    path: content/posts
    list:
      - title
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: slug
        label: Slug
        type: string
        hidden: true
      - name: date
        label: Date
        type: string
        hidden: true
      - name: type
        label: Type
        type: string
        hidden: true
      - name: description
        label: Description
        type: string
        hidden: true
      - name: seo_title
        label: SEO Title
        type: string
        hidden: true
      - name: image
        label: Featured Image
        type: image
      - name: body
        label: Body
        type: rich-text
