media:
  input: public/wp-content/uploads
  output: /wp-content/uploads

content:
  - name: posts
    label: Posts
    type: collection
    path: content/posts
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: image
        label: Featured Image
        type: image
      - name: body
        label: Body
        type: rich-text
