"use client";

import Link from 'next/link';
import { useState } from 'react';
import { Plus, Minus, ArrowRight } from 'lucide-react';

export default function Home() {
  const [openFaq, setOpenFaq] = useState<number | null>(0);

  const faqs = [
    { q: "How long does it take to process proof of funds?", a: "Typically, it takes 24-48 hours after all requirements are met." },
    { q: "What is a proof of funds letter?", a: "A letter from a bank stating you have enough funds to cover your travel and study expenses." },
    { q: "Do you have agents that can process UK Visas?", a: "Yes, we have partners that assist with the entire visa process." },
    { q: "Can I use real estate as proof of funds?", a: "Usually, liquid cash in a bank account is required, but some embassies accept property valuation." },
    { q: "Is the money kept in my account?", a: "Yes, the funds will be placed in an account in your name for the required duration." },
    { q: "What if I need the funds for a longer period?", a: "We offer flexible terms up to 6 months depending on the embassy's requirements." },
    { q: "Are the bank statements verifiable?", a: "Absolutely. All our bank statements are generated by top-tier Nigerian banks and are 100% verifiable." },
    { q: "Do you provide proof of funds for families?", a: "Yes, we can provide proof of funds that covers the principal applicant and all dependents." },
    { q: "What is the process to get started?", a: "Simply contact us, provide your passport details, and we'll guide you through the next steps." },
  ];

  return (
    <main className="min-h-screen bg-[#F3F0FF] text-[#120E00] font-sans">
      {/* 1. Hero Section */}
      <section className="bg-[#2E1499] text-white pt-20 pb-24 md:pt-0 md:pb-0 px-6 relative overflow-hidden">
        <div className="max-w-7xl mx-auto grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
          <div className="max-w-2xl relative z-10">
            <h1 className="text-5xl md:text-6xl font-serif font-bold mb-6 leading-[1.1]">
              Trusted Proof of<br/>Funds Agent in<br/>Nigeria
            </h1>
            <p className="text-lg text-indigo-100 mb-8 max-w-lg">
              We process low interest and highly verifiable POF loans for processing visas.
            </p>
            <div className="flex flex-col items-start gap-6">
              <a href="https://wa.link/a8pskc" target="_blank" rel="noopener noreferrer" className="bg-[#120E00] hover:bg-black text-white px-8 py-4 rounded font-medium border border-white/20 transition-all text-sm tracking-wider inline-flex items-center gap-2 w-fit">
                Chat us on WhatsApp
              </a>
              <div className="flex items-center gap-6">
                <Link href="/proof-of-fund-calculator" className="text-white hover:text-indigo-200 font-bold text-sm tracking-wide transition-colors underline underline-offset-4 decoration-white/70 hover:decoration-indigo-200">
                  POF CALCULATOR
                </Link>
                <Link href="/see-requirements" className="text-white hover:text-indigo-200 font-bold text-sm tracking-wide transition-colors underline underline-offset-4 decoration-white/70 hover:decoration-indigo-200">
                  SEE REQUIREMENTS
                </Link>
              </div>
            </div>
          </div>
          
          <div className="relative">
            <div className="relative rounded-3xl overflow-hidden">
              <img src="/wp-content/uploads/2025/09/Proof-of-Fund-in-Nigeria-1.webp" alt="Happy family traveling" className="w-full h-auto object-contain" />
            </div>
          </div>
        </div>
      </section>

      {/* 1.5 Marquee Section */}
      <div className="bg-[#120E00] py-4 overflow-hidden flex whitespace-nowrap border-b border-indigo-900/30">
        <div className="animate-marquee flex gap-16 items-center shrink-0 min-w-full">
          <span className="text-white font-medium text-sm md:text-base uppercase tracking-wider">Get Student Proof of Fund</span>
          <span className="text-blue-500 font-bold">•</span>
          <span className="text-white font-medium text-sm md:text-base uppercase tracking-wider">Get Immigration Proof of Fund</span>
          <span className="text-blue-500 font-bold">•</span>
          <span className="text-white font-medium text-sm md:text-base uppercase tracking-wider">Get Business Proof of Fund</span>
          <span className="text-blue-500 font-bold">•</span>
          <span className="text-white font-medium text-sm md:text-base uppercase tracking-wider">Get Real Estate Proof of Fund</span>
          <span className="text-blue-500 font-bold">•</span>
        </div>
        <div className="animate-marquee flex gap-16 items-center shrink-0 min-w-full pl-16" aria-hidden="true">
          <span className="text-white font-medium text-sm md:text-base uppercase tracking-wider">Get Student Proof of Fund</span>
          <span className="text-blue-500 font-bold">•</span>
          <span className="text-white font-medium text-sm md:text-base uppercase tracking-wider">Get Immigration Proof of Fund</span>
          <span className="text-blue-500 font-bold">•</span>
          <span className="text-white font-medium text-sm md:text-base uppercase tracking-wider">Get Business Proof of Fund</span>
          <span className="text-blue-500 font-bold">•</span>
          <span className="text-white font-medium text-sm md:text-base uppercase tracking-wider">Get Real Estate Proof of Fund</span>
          <span className="text-blue-500 font-bold">•</span>
        </div>
      </div>

      {/* 2. Services Grid */}
      <section className="py-24 px-6 bg-[#F3F0FF]">
        <div className="max-w-7xl mx-auto text-center">
          <h2 className="text-4xl font-serif font-bold text-[#120E00] mb-2">Discover Our Services</h2>
          <p className="text-slate-600 mb-16">We have unique POF structures tailored for your exact destination.</p>
          
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-y-12 gap-x-8 text-left">
            {[
              { title: "POF for Individuals", desc: "We provide verified proof of funds documentation that meets embassy and financial institution requirements, ensuring your visa or travel application process is smooth." },
              { title: "POF for Businesses", desc: "Whether for tenders, business expansion, or international transactions, we help businesses present credible proof of funds with complete documentation support." },
              { title: "Travel Loan for Travel Expenses", desc: "We offer flexible travel loan options to cover flight tickets, accommodation, and other essential expenses after your visa approval, giving you peace of mind as you prepare to relocate." },
              { title: "Investment Letter", desc: "We provide professionally issued investment letters in partnership with a fully registered and licensed finance company for visas, business deals, or official requirements." },
              { title: "Business/Car Loans", desc: "We help customers access flexible business and car loan options tailored to their needs. Whether they are expanding their company or purchasing a vehicle." },
              { title: "Other Loans You Need", desc: "We support customers with a wide range of financing options including invoice financing, contract financing, LPO financing, personal loans, and other loans" }
            ].map((service, i) => (
              <div key={i} className="bg-white rounded-3xl p-8 border-[3px] border-[#120E00] shadow-[-12px_12px_0px_#120E00] flex flex-col h-full">
                <h3 className="text-[1.75rem] leading-tight font-serif font-bold text-[#2E1499] mb-6">{service.title}</h3>
                <p className="text-[#120E00] text-[15px] leading-relaxed mb-8 flex-grow">{service.desc}</p>
                <Link href="/services" className="text-[#2E1499] font-black text-sm tracking-widest uppercase hover:text-blue-700 transition-colors">
                  LEARN MORE
                </Link>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* 3. How We Work */}
      <section className="py-20 px-6 bg-[#F3F0FF]">
        <div className="max-w-6xl mx-auto text-center">
          <h2 className="text-4xl md:text-5xl font-serif font-bold text-[#120E00] mb-16">Here is How We Work</h2>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-y-12 gap-x-8 text-left">
            <div className="bg-white rounded-3xl p-8 border-[3px] border-[#120E00] shadow-[-12px_12px_0px_#120E00] flex flex-col h-full">
              <span className="text-3xl font-serif italic text-[#2E1499] mb-4 block">1</span>
              <h3 className="text-[1.75rem] leading-tight font-serif font-bold text-[#2E1499] mb-6">Chat with us</h3>
              <p className="text-[#120E00] text-[15px] leading-relaxed mb-4 flex-grow">Tell us what you need a Proof of Fund for — business, real estate, student visa, or immigration.</p>
            </div>
            <div className="bg-white rounded-3xl p-8 border-[3px] border-[#120E00] shadow-[-12px_12px_0px_#120E00] flex flex-col h-full">
              <span className="text-3xl font-serif italic text-[#2E1499] mb-4 block">2</span>
              <h3 className="text-[1.75rem] leading-tight font-serif font-bold text-[#2E1499] mb-6">Get Best Option</h3>
              <p className="text-[#120E00] text-[15px] leading-relaxed mb-4 flex-grow">We'll connect you with the best finance house offering the best rate for your POF need.</p>
            </div>
            <div className="bg-white rounded-3xl p-8 border-[3px] border-[#120E00] shadow-[-12px_12px_0px_#120E00] flex flex-col h-full">
              <span className="text-3xl font-serif italic text-[#2E1499] mb-4 block">3</span>
              <h3 className="text-[1.75rem] leading-tight font-serif font-bold text-[#2E1499] mb-6">Get Funded</h3>
              <p className="text-[#120E00] text-[15px] leading-relaxed mb-4 flex-grow">Our partner finance house handle the process and ensure you receive a valid, verifiable POF.</p>
            </div>
          </div>
        </div>
      </section>

      {/* 4. Testimonial */}
      <section className="py-24 px-6 bg-[#F3F0FF]">
        <div className="max-w-7xl mx-auto">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            {[
              { name: "Ayo B.", handle: "@ayob_", text: "\"I recommend POFNG to every JAPA hunter in Nigeria because they are the most Affordable and Straight forward Agent in Nigeria.\"", date: "10:24 AM · Jul 20, 2026" },
              { name: "Chika N.", handle: "@chikan", text: "\"Fastest POF service I have ever used. Got my account funded in less than 24 hours. Highly recommended for students!\"", date: "2:15 PM · Aug 05, 2026" },
              { name: "Oluwaseun D.", handle: "@seun_d", text: "\"Their customer service is top notch. They guided me through the whole visa financial requirement process effortlessly.\"", date: "9:30 AM · Sep 12, 2026" },
              { name: "Emeka U.", handle: "@emeka_u", text: "\"Genuine and verifiable proof of funds. My UK business visa was approved without any financial document issues.\"", date: "4:45 PM · Oct 01, 2026" }
            ].map((item, index) => (
              <div key={index} className="bg-white rounded-2xl p-6 border border-slate-200 shadow-sm text-left flex flex-col h-full">
                <div className="flex items-center justify-between mb-4">
                  <div>
                    <p className="font-bold text-slate-900 leading-tight">{item.name}</p>
                    <p className="text-slate-500 text-sm">{item.handle}</p>
                  </div>
                  <img src="/logo.png" alt="POFNG" className="w-6 h-6 object-contain opacity-80" />
                </div>
                <p className="text-slate-800 text-base leading-normal mb-4 flex-grow">
                  {item.text}
                </p>
                <p className="text-slate-500 text-sm">
                  {item.date}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* 5. Features Strip */}
      <section className="bg-[#2E1499] py-20 px-6">
        <div className="max-w-7xl mx-auto">
          <div className="text-white mb-12 text-center md:text-left">
            <p className="text-lg font-serif mb-2 text-white/80">Why People Keep Choosing Us</p>
            <h2 className="text-4xl md:text-5xl font-serif font-bold leading-tight">We make it easy for everyone to meet their<br/>financial needs effortlessly.</h2>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {[
              { title: "Best Market Rates", desc: "Benefit from our strong affiliations and enjoy highly competitive rates." },
              { title: "Instant Processing", desc: "Receive funds within 24 hours (or up to 48 hours with some banks)." },
              { title: "Fund any Accounts", desc: "We can fund any bank account or set new one up for you. No delays." },
              { title: "Access ₦300M+", desc: "Get the exact amount you need, when you need it." }
            ].map((feat, i) => (
              <div key={i} className="bg-[#F3F0FF] rounded-3xl p-6 border-[3px] border-[#120E00] shadow-[-10px_10px_0px_#120E00] flex flex-col h-full text-left">
                <h4 className="font-bold font-serif text-[1.5rem] leading-tight text-[#2E1499] mb-3">{feat.title}</h4>
                <p className="text-[15px] text-[#120E00] leading-relaxed flex-grow">{feat.desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* 6. Video/Image Section */}
      <section className="py-24 px-6 bg-[#F3F0FF] overflow-hidden">
        <div className="max-w-5xl mx-auto text-center">
          <h2 className="text-3xl font-serif font-bold text-[#120E00] mb-12">Learn How Proof of Fund (POF)<br/>Works — Step by step</h2>
          <div className="relative rounded-3xl overflow-hidden h-[450px]">
            <img src="/wp-content/uploads/2025/09/Proof-of-Fund-in-Nigeria-1-1.webp" className="w-full h-full object-cover" alt="Proof of Funds Process" />
          </div>
        </div>
      </section>

      {/* 7. Blog Highlights */}
      <section className="py-24 px-6 bg-[#F3F0FF]">
        <div className="max-w-6xl mx-auto">
          <h2 className="text-3xl font-serif font-bold text-[#120E00] mb-12 text-center">Get to Know More About Proof of Funds</h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-x-8 gap-y-12">
            {/* Blog 1 */}
            <div className="bg-white rounded-3xl overflow-hidden border-[3px] border-[#120E00] shadow-[-10px_10px_0px_#120E00] flex flex-col h-full">
              <img src="/wp-content/uploads/2025/02/colleagues-studying-together-university-library_23-2148844695.jpg" alt="How to get POF" className="w-full h-48 object-cover border-b-[3px] border-[#120E00]" />
              <div className="p-6 flex flex-col flex-grow">
                <h3 className="font-bold text-[#120E00] mb-4 tracking-wide">HOW TO GET PROOF OF FUNDS IN NIGERIA</h3>
                <div className="mt-auto">
                  <Link href="/blog/how-to-get-proof-of-funds" className="text-sm font-black text-[#2E1499] hover:text-blue-700 transition-colors tracking-widest uppercase">READ MORE</Link>
                </div>
              </div>
            </div>
            {/* Blog 2 */}
            <div className="bg-white rounded-3xl overflow-hidden border-[3px] border-[#120E00] shadow-[-10px_10px_0px_#120E00] flex flex-col h-full">
              <img src="/wp-content/uploads/2025/02/tourist-carrying-baggage_23-2151747389.jpg" alt="Student Visa" className="w-full h-48 object-cover border-b-[3px] border-[#120E00]" />
              <div className="p-6 flex flex-col flex-grow">
                <h3 className="font-bold text-[#120E00] mb-4 tracking-wide">STUDENT VISA REQUIREMENTS FROM NIGERIA</h3>
                <div className="mt-auto">
                  <Link href="/blog/student-visa-requirements" className="text-sm font-black text-[#2E1499] hover:text-blue-700 transition-colors tracking-widest uppercase">READ MORE</Link>
                </div>
              </div>
            </div>
            {/* Blog 3 */}
            <div className="bg-white rounded-3xl overflow-hidden border-[3px] border-[#120E00] shadow-[-10px_10px_0px_#120E00] flex flex-col h-full">
              <img src="/wp-content/uploads/2025/02/two-business-woman-cafe_1157-14528.jpg" alt="List of Banks" className="w-full h-48 object-cover border-b-[3px] border-[#120E00]" />
              <div className="p-6 flex flex-col flex-grow">
                <h3 className="font-bold text-[#120E00] mb-4 tracking-wide">TOP LIST OF BANKS THAT PROVIDE LOANS IN NIGERIA</h3>
                <div className="mt-auto">
                  <Link href="/blog/top-list-of-banks" className="text-sm font-black text-[#2E1499] hover:text-blue-700 transition-colors tracking-widest uppercase">READ MORE</Link>
                </div>
              </div>
            </div>
          </div>
          
          <div className="mt-16 text-center">
            <Link href="/blog" className="inline-block bg-white text-[#120E00] border-[3px] border-[#120E00] shadow-[-6px_6px_0px_#120E00] hover:shadow-none hover:translate-x-[-6px] hover:translate-y-[6px] transition-all font-bold uppercase tracking-widest py-4 px-10 rounded-full">
              VIEW MORE POSTS
            </Link>
          </div>
        </div>
      </section>

      {/* 8. FAQ Section */}
      <section className="pt-24 pb-8 px-6 bg-[#F3F0FF]">
        <div className="max-w-3xl mx-auto">
          <h2 className="text-3xl font-serif font-bold text-[#120E00] mb-12 text-center">Frequently asked questions</h2>
          <div className="space-y-4">
            {faqs.map((faq, i) => (
              <div key={i} className="bg-white border border-slate-200 rounded-lg overflow-hidden">
                <button 
                  onClick={() => setOpenFaq(openFaq === i ? null : i)}
                  className="w-full px-6 py-4 flex justify-between items-center text-left focus:outline-none"
                >
                  <span className="font-bold text-[#2E1499] text-sm md:text-base">{faq.q}</span>
                  {openFaq === i ? <Minus size={20} className="text-blue-600 flex-shrink-0" /> : <Plus size={20} className="text-slate-400 flex-shrink-0" />}
                </button>
                <div className={`px-6 overflow-hidden transition-all duration-300 ease-in-out ${openFaq === i ? 'max-h-40 pb-4' : 'max-h-0'}`}>
                  <p className="text-slate-600 text-sm">{faq.a}</p>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

    </main>
  );
}